### ISSUE TITLE
Find good benchmarks

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#25]
We have an small set of benchmarks for evaluation that were made without thinking what are they measuring. It would be good to figure out how to measure the performance of each aspect of our current evaluation mode.

Edit: based on https://github.com/christianpoveda/pijama/issues/25#issuecomment-629462265. We need to add benchmarks doing:
- [x] A long math operation
- [x] A long short-circuiting logical expression
- [x] A long non short-circuiting logical expression
- [x] A complex chain of conditionals with boolean literals as conditions
- [x] A long chain of function calls.
- [x] Some classic functions:
  - [x] Factorial
  - [x] Fibonacci 
  - [x] Greatest common divisor
  - [x] Simple integer hash function

**Comment by DarkDrek** [comment]
I think we want some 'pure' benchmarks for specific features:
- A 'long' math operation
  - Probably with every operator we have times two or so to avoid cases where one operator is faster due to positioning
- A 'long' logical expression
  - One that is short circuiting and one that isn't
- A complex chain of `if ... else ...` with 'constant' conditionals 
- A lot of functions calling each other but no real computation
  - The arguments of the function should be complex
- A test using the beta-reduction (don't know much about that?)
- ...

And some 'classic' functional algorithms maybe even with a good and a naive implementation
- Factorial
- Fibonacci 
- Greatest common divisor
- Simple integer hash function (maybe we need bit shifts for that)

**Comment by pvdrz** [comment]
I added an small checklist with your suggestions. I have a couple questions:

> - A lot of functions calling each other but no real computation
>   - The arguments of the function should be complex

why complex arguments? to check how slow is to "move" large expressions between functions?

> Simple integer hash function (maybe we need bit shifts for that)

do you have any particular function in mind? I had [seahash](https://ticki.github.io/blog/seahash-explained/) in mind but as you said we need bit shifts for that :P

**Comment by DarkDrek** [comment]
Thanks for taking and implementing so many of my suggestions :+1:.

> why complex arguments? to check how slow is to "move" large expressions between functions?

Maybe there is a overhead with calling functions that have complex/lots of arguments compared to simple ones.

I don't have a particular hash function in mind. I just thought they are great non-trivial math/bit operations that tend to be rather well documented (often with an simple abstract implementation guide).

**Comment by pvdrz** [comment]
given that we have a call-by-name evaluation it is possible that moving complex terms is slower, but maybe having them behind boxes decreases the overhead. I'll do the test to see what happens

**Comment by pvdrz** [comment]
Ha! It actually matters! I added a new benchmark to https://github.com/christianpoveda/pijama/pull/32 with a conditional as the argument of the function and it is slightly slower than just passing a `1`.

I'll implement seahash with the new and shiny shift operators you added on a different PR. I'll merge this one when the tests finish running.

Update: I never implemented the hashing function. Got distracted :/
