### ISSUE TITLE
[Idea] Continuous benchmarking

### ISSUE THREAD

**Issue by DarkDrek** [pvdrz/pijama_legacy#59]
As a general 

Can we try https://github.com/rhysd/github-action-benchmark as a Github Action it support cargo bench but I'm not sure it does with criterion output.

If not it may be possible to build something with https://github.com/marketplace/actions/rust-cargo
witch checkout master run `cargo bench` checkout branch run `cargo bench` and posts the output.

This is just my quick research based on Github Actions... I have no experience using them 😄

Another idea is to run `cargo bench` on travis ci but so far there is no way of getting the output besides looking in the logs.

**Comment by pvdrz** [comment]
> Can we try https://github.com/rhysd/github-action-benchmark as a Github Action it support cargo bench but I'm not sure it does with criterion output.
>
> If not it may be possible to build something with https://github.com/marketplace/actions/rust-cargo
> witch checkout master run `cargo bench` checkout branch run `cargo bench` and posts the output.

this would be really really cool. I like it!

> This is just my quick research based on Github Actions... I have no experience using them smile

Heh, me neither but we are here to learn anyway :P

> Another idea is to run `cargo bench` on travis ci but so far there is no way of getting the output besides looking in the logs.

I've read that it is possible but it's not such a good idea because heavy load on Travis infrastructure can cause misleading results. It's on criterion docs iirc.

I'll tag it as something we need to figure out. It is completely worth doing the read.
