### ISSUE TITLE
Move to Rust stable

### ISSUE THREAD

**Issue by pvdrz** [pvdrz/pijama_legacy#60]
We use box patterns in the evaluation functions and on the test. But maybe it is worth checking if we can live without them and go back to stable.

**Comment by DarkDrek** [comment]
Rewriting our sources seems possible but we have a problem in the tests since there is no way in stable rust to match on the content of a `Box` we can't use the `matches!` macro to validate our nested types. One way to solve this is to do a string comparison of the result but then we lose the ability to ignore some content.

**Comment by pvdrz** [comment]
maybe we can get away with it in a similar way as with the parsing tests?

**Comment by DarkDrek** [comment]
I currently trying that if I have a compile-able state I will make a PR to discuss the approach.

**Comment by pvdrz** [comment]
closed via https://github.com/christianpoveda/pijama/pull/64
